//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Mini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int PersonId { get; set; }
        [Required(ErrorMessage = "please enter your First Name")]
        [StringLength(15, MinimumLength = 3)]
        [RegularExpression(@"^[a-zA-Z]+$")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "please enter your Middle Name")]
        [StringLength(15, MinimumLength = 3)]
        [RegularExpression(@"^[a-zA-Z]+$")]
        public string MiddleName { get; set; }

        [Required(ErrorMessage = "please enter your last Name")]
        [StringLength(15, MinimumLength = 3)]
        [RegularExpression(@"^[a-zA-Z]+$")]
        public string LastName { get; set; }

       
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        
        public System.DateTime AddedOn { get; set; }
        public string AddedBy { get; set; }

        [Required(ErrorMessage = "please enter your Home address")]
        public string HomeAddress { get; set; }

        [Required(ErrorMessage = "please enter your HomeCity")]
        [StringLength(20, MinimumLength = 3)]
        [RegularExpression(@"^[a-zA-Z]+$")]
        public string HomeCity { get; set; }

        [Required(ErrorMessage = "please enter your facebookId")]
        [RegularExpression(".+\\@.+", ErrorMessage = " Invalid Format, Kindly enter ID in valid format")]
        public string FaceBookAccountId { get; set; }

        [Required(ErrorMessage = "please enter your LinkedinId")]
        [RegularExpression(".+\\@.+", ErrorMessage = " Invalid Format, Kindly enter ID in valid format")]
        public string LinkedInId { get; set; }

        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string ImagePath { get; set; }

        [Required(ErrorMessage = "please enter your TwitterId")]
        [RegularExpression(".+\\@.+", ErrorMessage = " Invalid Format, Kindly enter ID in valid format")]
        public string TwitterId { get; set; }

        [Required(ErrorMessage = "please enter your GmailId")]
        [RegularExpression(".+\\@.+", ErrorMessage = " Invalid Format, Kindly enter ID in valid format")]
        public string EmailId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
